# Use the official .NET 8 SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy project files and restore dependencies
COPY ./API/*.csproj ./API/
RUN dotnet restore .

# Copy the rest of the files
COPY . .
WORKDIR /app/API

# Build the project
RUN dotnet build -c Release -o out

# Use the official .NET runtime image for running the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/API/out .

# Expose port 80 for the application
EXPOSE 80



# Set the entry point for the application
ENTRYPOINT ["dotnet", "API.dll"]
