# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Copy package.json and package-lock.json
COPY . /src/
WORKDIR /src/

# Install dependencies
RUN npm install

# Build the Next.js application
RUN ng serve

# Expose the port the app runs on
EXPOSE 3000
